default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: "/certs"

build:
  stage: build
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $QUAY_REGISTRY_USER -p $QUAY_REGISTRY_PASSWORD $QUAY_REGISTRY
  script:
    - docker build 
      --build-arg BASE_URL=$BASE_URL 
      --build-arg AUTH_TOKEN=$AUTH_TOKEN
      -t $QUAY_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHORT_SHA .
