# This YAML file defines the GitLab CI/CD pipeline configuration for the circle-partner-navigator-frontend project.

# Define the stages for the pipeline
stages:
  - build

# Build stage
build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --build-arg BASE_URL=$BASE_URL 
      --build-arg AUTH_TOKEN=$AUTH_TOKEN
      --no-push
