# This YAML file defines the GitLab CI/CD pipeline configuration for the circle-partner-navigator-frontend project.

# Define the stages for the pipeline
stages:
  - build


# Build stage
build:
  image: docker:cli
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  stage: build
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $QUAY_REGISTRY_USER -p $QUAY_REGISTRY_PASSWORD $QUAY_REGISTRY
  script:
    - docker build 
      --build-arg BASE_URL=$BASE_URL 
      --build-arg AUTH_TOKEN=$AUTH_TOKEN
      -t $QUAY_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHORT_SHA .
